countries/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home

app_name = "home"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("country/", include('country.urls')),
    path("", home, name="home"),
]

country/urls.py
from django.urls import path
from .views import (countries, cities, country_vote, CountryView, CountryResultsView, country_add, filter_by_country_and_population,
                    get_cities_population_more_than, filter_cities_by_country, country_view, delete_country)


app_name = "countries"

urlpatterns = [
    path("", countries, name='countries'),
    path("add", country_add, name='country_add'),
    path("<str:country_name>/delete", delete_country, name='delete_country'),
    path("cities", cities, name='cities'),
    path("cities/greater/<int:city_population>", get_cities_population_more_than, name='greater'),
    path("cities/<str:country_name>", filter_cities_by_country, name='by_country'),
    path("cities/<str:country_name>/greater/<int:city_population>", filter_by_country_and_population, name='by_country_and_pop'),
    path("", CountryView.as_view, name='countries'),
    path('<str:country_name>/vote', country_vote, name='countries_vote'),
    path('<str:country_name>/cities', country_view, name='country_cities'),
    path("<str:country>/results/", CountryResultsView.as_view(), name="country_view"),
]

country/models.py
import datetime
from django.db import models
from django.forms import forms, Textarea
from django.utils.timezone import now
class BaseModel(models.Model):
    objects = models.Manager()
    DoesNotExist = models.Manager()

    class Meta:
        abstract = True

class Country(BaseModel):
    continent_choices = {
        "europa":"Europe",
        "afrika":"Africa",
        "s_amerika": "North America",
        "p_amerika": "South America",
        "azija": "Asia",
        "australija":"Australia",
        "antarktida":"Antarctic"
    }
    country = models.CharField(max_length=50, unique=True)
    population = models.IntegerField(default=0)
    pub_date = models.DateTimeField(default=now)
    continent = models.CharField(max_length=50, choices=continent_choices)
    # description = models.CharField(widget=forms.Textarea)

    def __str__(self):
        return f'{self.country},   {str(self.population)}'

    def was_published_recently(self):
        return self.pub_date >= now() - datetime.timedelta(days=1)

class City(BaseModel):
    city = models.CharField(max_length=50)
    city_population = models.IntegerField(default=0)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    vote = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.city},  {self.country.country}'

country/forms.py
from django import forms
from django.forms import ModelForm

from country.models import Country

# class NameForm(forms.Form):
#     country = forms.CharField(label="Country name", max_length=100)
#     population = forms.IntegerField(label="Population")
#     continent = forms.CharField(label="Continent", max_length=100)


class NameForm(ModelForm):
    class Meta:
        model = Country
        fields = ["country", "population", "continent"]

countries/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

country/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import generic
from .models import Country, City
from .forms import NameForm, forms


def countries(request):
    countries_list = Country.objects.all()
    context = {'countries': countries_list}
    return render(request, 'country/countries.html', context)


def country_add(request):
    if request.method == "POST":
        form = NameForm(request.POST)
        if form.is_valid():
            country = form['country'].value()
            population = form['population'].value()
            continent = form['continent'].value()
            obj = Country(country=country, population=population, continent=continent)
            obj.save()
            return redirect('countries:countries')

    else:
        form = NameForm()
    context = {'form': form}
    return render(request, 'country/country_add.html', context)

def delete_country(request, country_name):
    if request.method == "POST":
        country = Country.objects.get(country=country_name)
        country.delete()
        return redirect("countries:countries")
    context = {'country': country_name}
    return render(request, 'country/country_delete.html', context)

class CountryView(generic.ListView):
    template_name = "country/countries.html"
    context_object_name = "countries"

    def get_queryset(self):
        return Country.objects.all()


def country_view(request, country_name):
    country = get_object_or_404(Country, country=country_name)
    context = {'country': country}
    return render(request, 'country/countries_cities.html', context)


class CountryResultsView(generic.DetailView):
    model = Country
    template_name = "country/countries_cities.html"

    def get_object(self, queryset=None):
        country = get_object_or_404(Country, country=self.kwargs.get("country"))
        return country


def country_vote(request, country_name):
    country = get_object_or_404(Country, country=country_name)
    try:
        selected_choice = country.city_set.get(pk=request.POST["choice"])
    except(KeyError, Country.DoesNotExist):
        context = {"country": country,
                   "error_message": "You didn't select a choice.",
                   }
        return render(request, "country/country.html", context=context)
    else:
        selected_choice.vote += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("countries:country_view", args=(country.country,)))


def cities(request):
    cities_list = City.objects.all()
    context = {'cities': cities_list, 'country':'all', 'population':0}
    return render(request, "country/cities.html", context)


def get_cities_population_more_than(request, city_population):
    bigger_cities = City.objects.filter(city_population__gte=city_population)
    context = {'cities': bigger_cities, 'population': city_population}
    return render(request, "country/cities.html", context)


def filter_cities_by_country(request, country_name):
    country = Country.objects.get(country=country_name)
    cities_by_country = City.objects.filter(country=country)
    context = {'cities': cities_by_country}
    return render(request, "country/cities.html", context)


def filter_by_country_and_population(request, country_name, city_population):
    if country_name == "all":
        cities = City.objects.filter(city_population__gte=city_population)
    else:
        country = Country.objects.get(country=country_name)
        cities = City.objects.filter(country=country, city_population__gte=city_population)
    context = {'cities': cities,'country':country_name}
    return render(request, "country/cities.html", context)

country/templates/country/cities.html
{% extends 'base.html' %}

{% block content %}
  {% if population > 0 %}
    <h1>CIA YRA NUFILTRUOTI MIESTAI, daugiau nei {{population}} gyventoju</h1>
  {% else %}
  <h1>CIA YRA VISI MIESTAI!</h1>
  {% endif %}


<body>
<h2>Cia yra cities page</h2>


    <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">City</th>
      <th scope="col">Country</th>
      <th scope="col">Population</th>
      <th scope="col">Vote</th>
    </tr>
  </thead>
  <tbody>
      {% for city in cities %}
        <tr>
          <th scope="row">{{forloop.counter}}</th>
          <td>{{city.city}}</td>
          <td><a href="{% url 'countries:by_country' city.country.country %}">{{ city.country.country}}</a></td>
          <td><a href="{% url 'countries:greater' city.city_population   %}">{{ city.city_population}}</a>
          <td>{{city.vote}}</td>
        </tr>
      {% endfor %}
  </tbody>
    </table>
</body>

{% endblock %}

country/templates/country/countries.html
{% extends 'base.html' %}

{% block content %}

    <h1>Countries</h1>
    {% for country in countries %}
        <li><a href="{% url 'countries:countries_vote' country.country %}">{{ country.country }}</a></li>
    {% endfor %}
    <br>
    <a class="btn btn-primary" href="{% url 'countries:country_add' %}" role="button">Add Country</a>
{% endblock %}

country/templates/country/countries_cities.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ country.country }}</h1>

<ul>
{% for city in country.city_set.all %}
    <li>{{ city.city }} -- {{ city.vote }} vote{{ city.vote|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'countries:countries_vote' country.country %}">Vote again?</a>
{% endblock %}

country/templates/country/country.html
{% extends 'base.html' %}

{% block content %}
    <form action="{% url 'countries:countries_vote' country.country %}" method="post">
        {% csrf_token %}
    <fieldset>
        <legend><h1> Tekstas </h1></legend>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            {% for city in country.city_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ city.id }}">
                <label for="choice{{ forloop.counter }}">{{ city.city }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
        <a class="btn btn-danger" href="{% url 'countries:delete_country' country.country %}" role="button">Delete Country</a>
    </form>
{% endblock %}

country/templates/country/country_add.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

country/templates/country/country_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>This is Country delete page</h1>
<h2>Are you sure you want to delete {{ country }} ?</h2>

<form action="" method="post">
     {% csrf_token %}
    <button type="submit" class="btn btn-danger" role="button">Yes</button>
</form>
    <a class="btn btn-primary" href="{% url 'countries:countries' %}" role="button">No</a>

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar bg-primary" data-bs-theme="dark">

      <div class="container">
          <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'home' %}">Home</a>
              <a class="navbar-brand" href="{% url 'countries:countries' %}">Countries</a>
              <a class="navbar-brand" href="{% url 'countries:cities' %}">Cities</a>
            </div>
          </nav>
      </div>

</nav>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}

<h2><> Cia yra home page  </h2>

{% endblock %}